services:
  app:
    image: wordpress:php8.1
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: test
      WORDPRESS_DB_PASSWORD: test
      WORDPRESS_DB_NAME: test
    ports:
      - 80
    volumes:
      - uploads:/var/www/html/wp-content/uploads
      - source: uploads
        target: /workspaces/uploads
        type: volume
        volume:
          nocopy: true
      - source: mysql
        target: /workspaces/mysql
        type: volume
        volume:
          nocopy: true
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - mysql:/var/lib/mysql
    entrypoint: "chown -R mysql:mysql /var/lib/mysql && /entrypoint.sh mysqld"

volumes:
  mysql:
  uploads:
